# Generated by Django 5.0.2 on 2024-02-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.BinaryField(),
        ),
    ]
