# Generated by Django 5.0.2 on 2024-02-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='session_hash',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
