# Generated by Django 5.0.2 on 2024-02-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='time_created',
            new_name='deadline',
        ),
    ]
