# Generated by Django 5.0.2 on 2024-02-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_time_created_list_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='user_hash',
            field=models.CharField(default='', max_length=255),
        ),
    ]
