# Generated by Django 5.0.2 on 2024-02-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_list_user_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='deadline',
            field=models.CharField(max_length=255),
        ),
    ]
