# Generated by Django 5.0.2 on 2024-02-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_list_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
