# Generated by Django 5.0.2 on 2024-02-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_rename__id_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='idd',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
